### PR TITLE
Change Future.delayed to Timer to prevent errors with undisposed timers

### PR DESCRIPTION
**Pull request by jxstxn1**
This Pull-Request Adress Issue #21 
I use this package in a bigger Project and my Tests failed all the Time due to an undisposed Timer.
So I replaced Future.delayed, which is under the Hood a Timer. And add it to a Timer variable.
I added it to the dispose Method to get rid of it.

Please let me know If I have to do any further changes or improvements

### CODE REVIEW

**Comment by jxstxn1** [comment]
Can you pls add the Hacktoberfest Tag

**Comment by maddyb99** [comment]
This project already has the Hacktoberfest topic added.
Will merge it now.
Also, can you post the error which you are facing since I cant seem to replicate it!

**Comment by jxstxn1** [comment]
> Thank you for pointing this out. Will merge ASAP



> This project already has the Hacktoberfest topic added.
> Will merge it now.
> Also, can you post the error which you are facing since I cant seem to replicate it?

yes of course

**Comment by maddyb99** [comment]
Hey, I'm merging this cause I like the change but I still want to see the error cause I was unable to reproduce it and no one else has reported it.

**Comment by jxstxn1** [comment]
> Hey, I'm merging this cause I like the change but I still want to see the error cause I was unable to reproduce it and no one else has reported it.

Im trying to make an Example without Production Code
And thanks for the merge

**Comment by maddyb99** [comment]
Thank you! I hope it doesn't take much of your time.
Just the error message should also do if it has enough info!

**Pull request merged**
